# Generated by Django 5.2.4 on 2025-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='unit_cost_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='unit_selling_price',
            field=models.IntegerField(),
        ),
    ]
