# Generated by Django 5.2.4 on 2025-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_classes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('social_name', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='entities', to='entity_classes.entityclass')),
            ],
        ),
    ]
